version: '3.8'

services:
  fortitoolbox:
    build: .
    container_name: fortitoolbox
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    restart: unless-stopped
